### ISSUE TITLE
Feature Request (missing/incomplete docs): Prerequisites

### ISSUE THREAD

**Issue by cb0s** [wuespace/telestion-docs#116]
### Type(/-s) of missing documentation

- [ ] Explanation of a concept
- [ ] Tutorial for achieving a task with the Telestion ecosystem
- [ ] Guide that explains how to use a specific tool in more detail
- [x] Reference to quickly look something up

### Description of missing documentation

We need to specify what you need to get started with Telestion. I mean things like Java-16+ for the telestion-core or NPM (_insert-version_) for the frontend to get started.

**Comment by pklaschka** [comment]
I changed the required type to reference as it suits the requested article better 😉
