### ISSUE TITLE
GUI Requirements D2

### ISSUE THREAD

**Issue by jvpichowski** [wuespace/telestion-docs#14]
We have to design the gui requirements for Daedalus 2. This document should be discussed with the D2 team, especially with @pklaschka as the Lead, and the Telestion team. This one is difficult because on the Telestion side @pklaschka is responsible for this too because of his role as advocate. We should add a second person in charge. I think @fussel178  is a good choice here.

**Comment by pklaschka** [comment]
Not relevant for this repository and no longer needed => closing this. If somebody still sees this requirement, please open an issue over in https://github.com/wuespace/telestion-project-daedalus2
