### ISSUE TITLE
A place for important notes

### ISSUE THREAD

**Issue by jvpichowski** [wuespace/telestion-docs#17]
How do we keep important notes? Look at the following example. I had this very important sentence about the configuration of clusters in networks. But I am sure I will not find it again on those big websites...

> Don’t forget that the Hazelcast cluster should live within one LAN. So even if you run the cluster on multiple Docker hosts, they should be located in one local network. If you need to synchronize Hazelcast data across multiple data centers, then have a look at the WAN Replication feature that is part of Hazelcast Enterprise. which you will need a license to access.

https://hazelcast.com/blog/configuring-hazelcast-in-non-orchestrated-docker-environments/

**Comment by pklaschka** [comment]
We have this place now in the "Internal Documentation" docs. I'm closing this issue 🙂
