### ISSUE TITLE
Describe organizational structure

### ISSUE THREAD

**Issue by jvpichowski** [wuespace/telestion-docs#26]
We should include the organizational structure into the documentation.
WHich tag fits best? @pklaschka 

![grafik](https://user-images.githubusercontent.com/18517811/89987093-b988e280-dc7d-11ea-9d7d-2205c4eaf882.png)

**Comment by pklaschka** [comment]
Now done through video series that's already a part of the documentation and a mix of other issues (such as #119) => closing this
