### ISSUE TITLE
Add meeting organization to documentation

### ISSUE THREAD

**Issue by jvpichowski** [wuespace/telestion-docs#70]

**Comment by pklaschka** [comment]
@jvpichowski @fussel178 Is @jvpichowski as assignee still correct?

**Comment by fussel178** [comment]
We have a well written meeting organization by @jvpichowski here:
https://github.com/wuespace/telestion/wiki/Meeting-Organization

Do we want to include that in the official documentation?

**Comment by pklaschka** [comment]
I don't think we need it. Closing this issue now 🙂
