### ISSUE TITLE
Java doc to Docusaurus v2 / Markdown

### ISSUE THREAD

**Issue by jvpichowski** [wuespace/telestion-docs#76]

**Comment by cb0s** [comment]
@pklaschka is this still open? I mean we switched to a different system, right?

**Comment by pklaschka** [comment]
@cb0s I would say that it's still open, only the "target system" has changed to Markdown/Docusaurus v2 😉

**Comment by pklaschka** [comment]
I'm de-prioritizing this. Let's work on a structure where we can use "native" JavaDoc references for now. Better integration might still be a consideration sometime in the (not so near) future, but I'm closing this as I no longer want to track this for the time being.
